version: '3'

services:
  api:
    container_name: watchedseries_api
    restart: always
    build:
      dockerfile: ./Dockerfile
      context: .
    ports:
      - 3333:3333
    command: yarn dev
    volumes:
      - .:/home/watchedseries
      - /home/watchedseries/node_modules
    environment:
      TYPEORM_HOST: database
      JWT_PRIVATE_KEY: -----BEGIN RSA PRIVATE KEY-----\nMIIEogIBAAKCAQEAzfILXRat+8cfJcZgwzqqDtsKllOlN8J0VPQcQVxv3mDqzN5m\nPwmzYDbiqyqqUCy+3Sq6wL9+lez48d0E2qi0jspsCSn/xidn+ZtBjAribgurUjs2\nu4wlGkQmZhVXEmaHDXmZBW6BlgOY+1QXvKHgZothtu/WCIxTslrS/W2fo+sLLKtt\ntJbSJgh1HHzPs4JIucKx0h2jzJ31Fx7MlzcM+ScNrV0eYMwEDtsz8RqNqFs4BrB7\nJJCMFJVr/91atdX/+BlmkBL14PFV7N8b7TqEsNH0S4Zriv6Jamyu3fxbvFcnbo9W\nhymbrMwnO8+VGAoA20bZS2kiu4dDzlpGTZdBZwIDAQABAoIBACIASCgCSo86/MV7\nzxXsZY82UrUm8iwWiqZL9y5DWKTaU2mnfjICI/9KkHm5/YxnFsvk9hhEhV2zVhZ4\nawi+ubCpctTAfl30u5HWNCgu09tfSdW1uP+Vz7pabgyEkW+URc/Pt5fR+ssNpQA5\njgGyqB3F/Uf6qNeYc2kK3bLBmo2xQGfaNA4ufVqVu9RsU4A9Ba6ZjgiTn+HOUHmi\nANIGeG+9QhyZcMOcVTOjWNLFNp5NMFBy+ser9LvMf/SdG3g+KV+nr1cD4IfSS+6H\nDxIvhR6WmGah3dN3QSz1cGfq50BxEHwUOM6BuMtdy7z5D5coq//t0lC0ilWdG8Kx\nT5gxMuECgYEA/Md10kAhuYXB8QLSn/9sQCBlxVdLYzd6k6oDgpxLIPEHiM0wJ/2l\nPQUUsRJlNfSngeJiPn1HqeSo23u3B4Uiu73Y0kA5itvV/Exf9u3guTFPdee/csiW\nodHt8m3wbd4MuEoy9sftaAseVsT4p5CgjFxQC3wC5G5o3k1RUl4ChzMCgYEA0JHR\nSp+lwH3A7CcZlDKDG4kymtmcZDpTr/pwgE12y2xmpOoflgT1i7Mq0Xcf37XiHhyo\nEW9h9BRzDZp1oYUUhIoaXmXrOJWN9uX8aNMXwMEBzs3ov0gbIwY3D8h0zzh5ivBj\nEo0ca1k36iQC08gjoYe484L1K/we1lGwmZ05zP0CgYBZA0wEG71EfUuMOTg+S02t\nTztHQLQ1XgX2FbpitfLmyLmkfMzmaDVVxYJB0H5/f4W1ASkjZC5mLzUfBPOw3Dsc\n7X96mk8pDLzPuX1ZkO6/iBO5K0CJhQU2OpyV8AzoQ3crNkW4DTMWnkOyvm3pY86F\nXsR5JtRF6HNZRNTMMnqlbQKBgFkb869ORiLXl3VNvz/x1NIO6+/8yTSJNvgYp7gp\nYHfI+JG89YHC3KWzBrg3jQanTtROqf/I9rCxi/Zj5536namC14E9SiICw4SY/h5L\nEfroez0//BC9Xdq47Q1xN3bRShxyV+G1KE807w66E/snpxF8Syi+6sDAFuy6Ohln\ncyqBAoGAKIlSxCnTCFUPax9qTXK5/iYGSkbaQGG/IV1evgvUSkahJFRWBhrtyLlo\nn6Lv35jzbVhwVJzqkLZnQ4JEi13BQqHIsi6HzKjL2eOCCR6DtaySSy8DDK1X+3tf\nAdYbYHRV6Z5lI48qwK1nCoreCeBfKMnI9eq+CSkigunyCjeUfV8=\n-----END RSA PRIVATE KEY-----
      JWT_PUBLIC_KEY: -----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAzfILXRat+8cfJcZgwzqq\nDtsKllOlN8J0VPQcQVxv3mDqzN5mPwmzYDbiqyqqUCy+3Sq6wL9+lez48d0E2qi0\njspsCSn/xidn+ZtBjAribgurUjs2u4wlGkQmZhVXEmaHDXmZBW6BlgOY+1QXvKHg\nZothtu/WCIxTslrS/W2fo+sLLKtttJbSJgh1HHzPs4JIucKx0h2jzJ31Fx7MlzcM\n+ScNrV0eYMwEDtsz8RqNqFs4BrB7JJCMFJVr/91atdX/+BlmkBL14PFV7N8b7TqE\nsNH0S4Zriv6Jamyu3fxbvFcnbo9WhymbrMwnO8+VGAoA20bZS2kiu4dDzlpGTZdB\nZwIDAQAB\n-----END PUBLIC KEY-----


  database:
    container_name: watchedseries_db
    image: postgres:13.1
    environment:
      POSTGRES_PASSWORD: watchedseries
      POSTGRES_USER: postgres
      POSTGRES_DB: watchedseries
    ports:
      - 5432:5432
