version: '3'

services:
  api:
    container_name: watchedseries_api
    restart: always
    build:
      dockerfile: ./Dockerfile
      context: .
    ports:
      - 3333:3333
    command: yarn dev
    volumes:
      - .:/home/watchedseries
      - /home/watchedseries/node_modules
    environment:
      TYPEORM_HOST: database

  database:
    container_name: watchedseries_db
    image: postgres:13.1
    environment:
      POSTGRES_PASSWORD: watchedseries
      POSTGRES_USER: postgres
      POSTGRES_DB: watchedseries
    ports:
      - 5432:5432
